### ISSUE TITLE
Accesibilidad - Crear album

### ISSUE THREAD

**Issue by duvanjamidvc** [navi-dupli/app-movil#81]
Contraste del texto
[81,618][352,655]
La relación de contraste del texto del elemento es 2,58. Esta cifra se basa en una estimación del color #8B8B8B del primer plano y del color #E0E0E0 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

Contraste del texto
[498,2291][582,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

Contraste del texto
[867,2291][934,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

![screen2](https://user-images.githubusercontent.com/98790557/204917398-91f5cc52-046e-485e-8217-3ea7462072be.png)

**Comment by mviviana** [comment]
Resultado de la mejora de accesibilidad
![image](https://user-images.githubusercontent.com/98857876/204946569-c59e92ac-4afe-48e1-b91c-3cea4448e80c.png)
