### ISSUE TITLE
Accesibilidad - Asociar Track

### ISSUE THREAD

**Issue by duvanjamidvc** [navi-dupli/app-movil#82]
A continuación, encontrarás una lista de oportunidades para mejorar la accesibilidad de Vinilos. Cada elemento corresponde a un área descrita en la captura de pantalla adjunta.

Contraste del texto
[125,2291][235,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

Contraste del texto
[867,2291][934,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

![screen6](https://user-images.githubusercontent.com/98790557/204917928-6425cec6-f3c1-4561-ab14-5cffa4867efa.png)

**Comment by nataliesantiagou** [comment]
Resultado mejora de accesibilidad ventana de asociar tracks
![Screenshot_20221130-170809](https://user-images.githubusercontent.com/98624496/204936365-d7f766dd-0e10-4e71-a082-c816dfa47f41.png)
