### ISSUE TITLE
Accesibilidad - Barra de navegación 

### ISSUE THREAD

**Issue by duvanjamidvc** [navi-dupli/app-movil#83]
A continuación, encontrarás una lista de oportunidades para mejorar la accesibilidad de Vinilos. Cada elemento corresponde a un área descrita en la captura de pantalla adjunta.

Contraste del texto
[356,2291][455,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

Contraste del texto
[583,2291][767,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

Contraste del texto
[912,2291][979,2328]
La relación de contraste del texto del elemento es 3,66. Esta cifra se basa en una estimación del color #666666 del primer plano y del color #000000 del segundo plano. Te recomendamos que uses colores que aumenten la relación de contraste más de 4,50 para textos de pequeño tamaño o a 3,00 para textos de gran tamaño.

![screen14](https://user-images.githubusercontent.com/98790557/204918260-cc8003a8-25ad-45a7-aa61-c138fd04fa0d.png)
![screen16](https://user-images.githubusercontent.com/98790557/204918281-6303edff-1588-4917-8a33-e3bd697c79d8.png)

**Comment by p-grijalbar** [comment]
Resultado mejora de accesibilidad barra de navegación
![Screenshot_20221130-170739](https://user-images.githubusercontent.com/98624500/204936758-912df118-3530-414f-9767-3fafb6396bbc.png)
![Screenshot_20221130-170755](https://user-images.githubusercontent.com/98624500/204936767-ed833d12-4cee-487e-b7be-d9bc4cafe5ac.png)
